
/**
 * Copyright 2017 Google Inc. All rights reserved.
 * Modifications copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by generate_keyboard_layouts.js, do not edit manually.

import type { KeyboardLayout } from '../types';

// KLID 0000044B - Kannada keyboard
const keyboardLayout: KeyboardLayout = {
  Escape: { key: 'Escape', keyCode: 27 },
  F1: { key: 'F1', keyCode: 112 },
  F2: { key: 'F2', keyCode: 113 },
  F3: { key: 'F3', keyCode: 114 },
  F4: { key: 'F4', keyCode: 115 },
  F5: { key: 'F5', keyCode: 116 },
  F6: { key: 'F6', keyCode: 117 },
  F7: { key: 'F7', keyCode: 118 },
  F8: { key: 'F8', keyCode: 119 },
  F9: { key: 'F9', keyCode: 120 },
  F10: { key: 'F10', keyCode: 121 },
  F11: { key: 'F11', keyCode: 122 },
  F12: { key: 'F12', keyCode: 123 },
  Backquote: { key: 'ೊ', keyCode: 192, shiftKey: 'ಒ' },
  Digit1: { key: '1', keyCode: 49 },
  Digit2: { key: '2', keyCode: 50 },
  Digit3: { key: '3', keyCode: 51, shiftKey: '್' },
  Digit4: { key: '4', keyCode: 52, shiftKey: 'ರ' },
  Digit5: { key: '5', keyCode: 53, shiftKey: 'ಜ' },
  Digit6: { key: '6', keyCode: 54, shiftKey: 'ತ' },
  Digit7: { key: '7', keyCode: 55, shiftKey: 'ಕ' },
  Digit8: { key: '8', keyCode: 56, shiftKey: 'ಶ' },
  Digit9: { key: '9', keyCode: 57, shiftKey: '(' },
  Digit0: { key: '0', keyCode: 48, shiftKey: ')' },
  Minus: { key: '-', keyCode: 189, shiftKey: 'ಃ' },
  Equal: { key: 'ೃ', keyCode: 187, shiftKey: 'ಋ' },
  Backspace: { key: 'Backspace', keyCode: 8 },
  Tab: { key: 'Tab', keyCode: 9 },
  KeyQ: { key: 'ೌ', keyCode: 81, shiftKey: 'ಔ' },
  KeyW: { key: 'ೈ', keyCode: 87, shiftKey: 'ಐ' },
  KeyE: { key: 'ಾ', keyCode: 69, shiftKey: 'ಆ' },
  KeyR: { key: 'ೀ', keyCode: 82, shiftKey: 'ಈ' },
  KeyT: { key: 'ೂ', keyCode: 84, shiftKey: 'ಊ' },
  KeyY: { key: 'ಬ', keyCode: 89, shiftKey: 'ಭ' },
  KeyU: { key: 'ಹ', keyCode: 85, shiftKey: 'ಙ' },
  KeyI: { key: 'ಗ', keyCode: 73, shiftKey: 'ಘ' },
  KeyO: { key: 'ದ', keyCode: 79, shiftKey: 'ಧ' },
  KeyP: { key: 'ಜ', keyCode: 80, shiftKey: 'ಝ' },
  BracketLeft: { key: 'ಡ', keyCode: 219, shiftKey: 'ಢ' },
  BracketRight: { keyCode: 221, shiftKey: 'ಞ' },
  Enter: { key: 'Enter', keyCode: 13, text: '\r' },
  CapsLock: { key: 'CapsLock', keyCode: 20 },
  KeyA: { key: 'ೋ', keyCode: 65, shiftKey: 'ಓ' },
  KeyS: { key: 'ೇ', keyCode: 83, shiftKey: 'ಏ' },
  KeyD: { key: '್', keyCode: 68, shiftKey: 'ಅ' },
  KeyF: { key: 'ಿ', keyCode: 70, shiftKey: 'ಇ' },
  KeyG: { key: 'ು', keyCode: 71, shiftKey: 'ಉ' },
  KeyH: { key: 'ಪ', keyCode: 72, shiftKey: 'ಫ' },
  KeyJ: { key: 'ರ', keyCode: 74, shiftKey: 'ಱ' },
  KeyK: { key: 'ಕ', keyCode: 75, shiftKey: 'ಖ' },
  KeyL: { key: 'ತ', keyCode: 76, shiftKey: 'ಥ' },
  Semicolon: { key: 'ಚ', keyCode: 186, shiftKey: 'ಛ' },
  Quote: { key: 'ಟ', keyCode: 222, shiftKey: 'ಠ' },
  ShiftLeft: { key: 'Shift', keyCode: 160, keyCodeWithoutLocation: 16, location: 1 },
  KeyZ: { key: 'ೆ', keyCode: 90, shiftKey: 'ಎ' },
  KeyX: { key: 'ಂ', keyCode: 88 },
  KeyC: { key: 'ಮ', keyCode: 67, shiftKey: 'ಣ' },
  KeyV: { key: 'ನ', keyCode: 86 },
  KeyB: { key: 'ವ', keyCode: 66 },
  KeyN: { key: 'ಲ', keyCode: 78, shiftKey: 'ಳ' },
  KeyM: { key: 'ಸ', keyCode: 77, shiftKey: 'ಶ' },
  Comma: { key: ',', keyCode: 188, shiftKey: 'ಷ' },
  Period: { key: '.', keyCode: 190, shiftKey: '|' },
  Slash: { key: 'ಯ', keyCode: 191 },
  ShiftRight: { key: 'Shift', keyCode: 161, keyCodeWithoutLocation: 16, location: 2 },
  ControlLeft: { key: 'Control', keyCode: 162, keyCodeWithoutLocation: 17, location: 1 },
  MetaLeft: { key: 'Meta', keyCode: 91, location: 1 },
  AltLeft: { key: 'Alt', keyCode: 164, keyCodeWithoutLocation: 18, location: 1 },
  Space: { key: ' ', keyCode: 32 },
  AltRight: { key: 'Alt', keyCode: 165, keyCodeWithoutLocation: 18, location: 2 },
  AltGraph: { key: 'AltGraph', keyCode: 225 },
  MetaRight: { key: 'Meta', keyCode: 92, location: 2 },
  ContextMenu: { key: 'ContextMenu', keyCode: 93 },
  ControlRight: { key: 'Control', keyCode: 163, keyCodeWithoutLocation: 17, location: 2 },
  PrintScreen: { key: 'PrintScreen', keyCode: 44 },
  ScrollLock: { key: 'ScrollLock', keyCode: 145 },
  Pause: { key: 'Pause', keyCode: 19 },
  PageUp: { key: 'PageUp', keyCode: 33 },
  PageDown: { key: 'PageDown', keyCode: 34 },
  Insert: { key: 'Insert', keyCode: 45 },
  Delete: { key: 'Delete', keyCode: 46 },
  Home: { key: 'Home', keyCode: 36 },
  End: { key: 'End', keyCode: 35 },
  ArrowLeft: { key: 'ArrowLeft', keyCode: 37 },
  ArrowUp: { key: 'ArrowUp', keyCode: 38 },
  ArrowRight: { key: 'ArrowRight', keyCode: 39 },
  ArrowDown: { key: 'ArrowDown', keyCode: 40 },
  NumLock: { key: 'NumLock', keyCode: 144 },
  NumpadDivide: { key: '/', keyCode: 111, location: 3 },
  NumpadMultiply: { key: '*', keyCode: 106, location: 3 },
  NumpadSubtract: { key: '-', keyCode: 109, location: 3 },
  Numpad7: { key: 'Home', keyCode: 36, shiftKey: '7', shiftKeyCode: 103, location: 3 },
  Numpad8: { key: 'ArrowUp', keyCode: 38, shiftKey: '8', shiftKeyCode: 104, location: 3 },
  Numpad9: { key: 'PageUp', keyCode: 33, shiftKey: '9', shiftKeyCode: 105, location: 3 },
  Numpad4: { key: 'ArrowLeft', keyCode: 37, shiftKey: '4', shiftKeyCode: 100, location: 3 },
  Numpad5: { key: 'Clear', keyCode: 12, shiftKey: '5', shiftKeyCode: 101, location: 3 },
  Numpad6: { key: 'ArrowRight', keyCode: 39, shiftKey: '6', shiftKeyCode: 102, location: 3 },
  NumpadAdd: { key: '+', keyCode: 107, location: 3 },
  Numpad1: { key: 'End', keyCode: 35, shiftKey: '1', shiftKeyCode: 97, location: 3 },
  Numpad2: { key: 'ArrowDown', keyCode: 40, shiftKey: '2', shiftKeyCode: 98, location: 3 },
  Numpad3: { key: 'PageDown', keyCode: 34, shiftKey: '3', shiftKeyCode: 99, location: 3 },
  Numpad0: { key: 'Insert', keyCode: 45, shiftKey: '0', shiftKeyCode: 96, location: 3 },
  NumpadDecimal: { key: '\u0000', keyCode: 46, shiftKey: '.', shiftKeyCode: 110, location: 3 },
  NumpadEnter: { key: 'Enter', keyCode: 13, text: '\r', location: 3 },
};

export default keyboardLayout;