
/**
 * Copyright 2017 Google Inc. All rights reserved.
 * Modifications copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by generate_keyboard_layouts.js, do not edit manually.

import type { KeyboardLayout } from '../types';

// KLID 0000045C - Cherokee Nation keyboard
const keyboardLayout: KeyboardLayout = {
  Escape: { key: 'Escape', keyCode: 27 },
  F1: { key: 'F1', keyCode: 112 },
  F2: { key: 'F2', keyCode: 113 },
  F3: { key: 'F3', keyCode: 114 },
  F4: { key: 'F4', keyCode: 115 },
  F5: { key: 'F5', keyCode: 116 },
  F6: { key: 'F6', keyCode: 117 },
  F7: { key: 'F7', keyCode: 118 },
  F8: { key: 'F8', keyCode: 119 },
  F9: { key: 'F9', keyCode: 120 },
  F10: { key: 'F10', keyCode: 121 },
  F11: { key: 'F11', keyCode: 122 },
  F12: { key: 'F12', keyCode: 123 },
  Backquote: { key: '`', keyCode: 222, shiftKey: 'Ꮚ' },
  Digit1: { key: 'Digit1', keyCode: 49, shiftKey: 'Ꮁ' },
  Digit2: { key: 'Digit2', keyCode: 50, shiftKey: 'Ꮗ' },
  Digit3: { key: 'Digit3', keyCode: 51, shiftKey: 'Ꮷ' },
  Digit4: { key: 'Ꮩ', keyCode: 52, shiftKey: 'Ꮀ' },
  Digit5: { key: 'Ꮶ', keyCode: 53, shiftKey: 'Ꮉ' },
  Digit6: { key: 'Ꮬ', keyCode: 54, shiftKey: 'Ꮭ' },
  Digit7: { key: 'Ꮛ', keyCode: 55, shiftKey: 'Ꮱ' },
  Digit8: { key: 'Ꮦ', keyCode: 56, shiftKey: 'Ꮊ' },
  Digit9: { key: 'Ꮢ', keyCode: 57, shiftKey: '(' },
  Digit0: { key: 'Ꮔ', keyCode: 48, shiftKey: ')' },
  Minus: { key: 'Ꮏ', keyCode: 189, shiftKey: 'Ꮌ' },
  Equal: { key: 'Ᏻ', keyCode: 187, shiftKey: 'Ꮍ' },
  Backspace: { key: 'Backspace', keyCode: 8 },
  Tab: { key: 'Tab', keyCode: 9 },
  KeyQ: { key: 'Ꭺ', keyCode: 81, shiftKey: 'Ꮖ' },
  KeyW: { key: 'Ꮃ', keyCode: 87, shiftKey: 'Ꮻ' },
  KeyE: { key: 'Ꭱ', keyCode: 69, shiftKey: 'Ꮳ' },
  KeyR: { key: 'Ꮫ', keyCode: 82, shiftKey: 'Ꮟ' },
  KeyT: { key: 'Ꮤ', keyCode: 84, shiftKey: 'Ꮨ' },
  KeyY: { key: 'Ꮿ', keyCode: 89, shiftKey: 'Ᏺ' },
  KeyU: { key: 'Ꭴ', keyCode: 85, shiftKey: 'Ꭽ' },
  KeyI: { key: 'Ꭲ', keyCode: 73, shiftKey: 'Ᏹ' },
  KeyO: { key: 'Ꭳ', keyCode: 79, shiftKey: 'Ꮼ' },
  KeyP: { key: 'Ꮑ', keyCode: 80, shiftKey: 'Ꮺ' },
  BracketLeft: { key: 'Ꮥ', keyCode: 219, shiftKey: 'Ꮡ' },
  BracketRight: { key: 'Ꮆ', keyCode: 221, shiftKey: 'Ꮴ' },
  Enter: { key: 'Enter', keyCode: 13, text: '\r' },
  CapsLock: { key: 'CapsLock', keyCode: 20 },
  KeyA: { key: 'Ꭰ', keyCode: 65, shiftKey: 'Ꮜ' },
  KeyS: { key: 'Ꮝ', keyCode: 83, shiftKey: 'Ꮞ' },
  KeyD: { key: 'Ꮧ', keyCode: 68, shiftKey: 'Ꮠ' },
  KeyF: { key: 'Ꭹ', keyCode: 70, shiftKey: 'Ꮘ' },
  KeyG: { key: 'Ꭶ', keyCode: 71, shiftKey: 'Ꮵ' },
  KeyH: { key: 'Ꭿ', keyCode: 72, shiftKey: 'Ꮂ' },
  KeyJ: { key: 'Ꮪ', keyCode: 74, shiftKey: 'Ꭻ' },
  KeyK: { key: 'Ꮈ', keyCode: 75, shiftKey: 'Ꭷ' },
  KeyL: { key: 'Ꮅ', keyCode: 76, shiftKey: 'Ꭾ' },
  Semicolon: { key: 'Ꮸ', keyCode: 186, shiftKey: 'Ꮰ' },
  Quote: { key: '\'', keyCode: 192, shiftKey: '"' },
  Backslash: { key: 'Ꮹ', keyCode: 220, shiftKey: 'Ꮾ' },
  ShiftLeft: { key: 'Shift', keyCode: 160, keyCodeWithoutLocation: 16, location: 1 },
  KeyZ: { key: 'Ꭼ', keyCode: 90, shiftKey: 'Ꮓ' },
  KeyX: { key: 'Ᏼ', keyCode: 88, shiftKey: 'Ꮽ' },
  KeyC: { key: 'Ꮣ', keyCode: 67, shiftKey: 'Ꮯ' },
  KeyV: { key: 'Ꭵ', keyCode: 86, shiftKey: 'Ꮮ' },
  KeyB: { key: 'Ꭸ', keyCode: 66, shiftKey: 'Ᏸ' },
  KeyN: { key: 'Ꮎ', keyCode: 78, shiftKey: 'Ꮋ' },
  KeyM: { key: 'Ꮕ', keyCode: 77, shiftKey: 'Ꮇ' },
  Comma: { key: ',', keyCode: 188, shiftKey: 'Ꮲ' },
  Period: { key: '.', keyCode: 190, shiftKey: 'Ꮄ' },
  Slash: { key: 'Ꮒ', keyCode: 191, shiftKey: 'Ꮙ' },
  ShiftRight: { key: 'Shift', keyCode: 161, keyCodeWithoutLocation: 16, location: 2 },
  ControlLeft: { key: 'Control', keyCode: 162, keyCodeWithoutLocation: 17, location: 1 },
  MetaLeft: { key: 'Meta', keyCode: 91, location: 1 },
  AltLeft: { key: 'Alt', keyCode: 164, keyCodeWithoutLocation: 18, location: 1 },
  Space: { key: ' ', keyCode: 32 },
  AltRight: { key: 'Alt', keyCode: 165, keyCodeWithoutLocation: 18, location: 2 },
  AltGraph: { key: 'AltGraph', keyCode: 225 },
  MetaRight: { key: 'Meta', keyCode: 92, location: 2 },
  ContextMenu: { key: 'ContextMenu', keyCode: 93 },
  ControlRight: { key: 'Control', keyCode: 163, keyCodeWithoutLocation: 17, location: 2 },
  PrintScreen: { key: 'PrintScreen', keyCode: 44 },
  ScrollLock: { key: 'ScrollLock', keyCode: 145 },
  Pause: { key: 'Pause', keyCode: 19 },
  PageUp: { key: 'PageUp', keyCode: 33 },
  PageDown: { key: 'PageDown', keyCode: 34 },
  Insert: { key: 'Insert', keyCode: 45 },
  Delete: { key: 'Delete', keyCode: 46 },
  Home: { key: 'Home', keyCode: 36 },
  End: { key: 'End', keyCode: 35 },
  ArrowLeft: { key: 'ArrowLeft', keyCode: 37 },
  ArrowUp: { key: 'ArrowUp', keyCode: 38 },
  ArrowRight: { key: 'ArrowRight', keyCode: 39 },
  ArrowDown: { key: 'ArrowDown', keyCode: 40 },
  NumLock: { key: 'NumLock', keyCode: 144 },
  NumpadDivide: { key: '/', keyCode: 111, location: 3 },
  NumpadMultiply: { key: '*', keyCode: 106, location: 3 },
  NumpadSubtract: { key: '-', keyCode: 109, location: 3 },
  Numpad7: { key: 'Home', keyCode: 36, shiftKey: '7', shiftKeyCode: 103, location: 3 },
  Numpad8: { key: 'ArrowUp', keyCode: 38, shiftKey: '8', shiftKeyCode: 104, location: 3 },
  Numpad9: { key: 'PageUp', keyCode: 33, shiftKey: '9', shiftKeyCode: 105, location: 3 },
  Numpad4: { key: 'ArrowLeft', keyCode: 37, shiftKey: '4', shiftKeyCode: 100, location: 3 },
  Numpad5: { key: 'Clear', keyCode: 12, shiftKey: '5', shiftKeyCode: 101, location: 3 },
  Numpad6: { key: 'ArrowRight', keyCode: 39, shiftKey: '6', shiftKeyCode: 102, location: 3 },
  NumpadAdd: { key: '+', keyCode: 107, location: 3 },
  Numpad1: { key: 'End', keyCode: 35, shiftKey: '1', shiftKeyCode: 97, location: 3 },
  Numpad2: { key: 'ArrowDown', keyCode: 40, shiftKey: '2', shiftKeyCode: 98, location: 3 },
  Numpad3: { key: 'PageDown', keyCode: 34, shiftKey: '3', shiftKeyCode: 99, location: 3 },
  Numpad0: { key: 'Insert', keyCode: 45, shiftKey: '0', shiftKeyCode: 96, location: 3 },
  NumpadDecimal: { key: '\u0000', keyCode: 46, shiftKey: '.', shiftKeyCode: 110, location: 3 },
  NumpadEnter: { key: 'Enter', keyCode: 13, text: '\r', location: 3 },
};

export default keyboardLayout;