/**
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by generate_keyboard_layouts.js, do not edit manually.

import defaultKeyboardLayoutObject from './layouts/00000409';
import type { KeyboardLayout } from './types';

export type * from './types';
export const defaultKlid = '00000409';
export const defaultKeyboardLayout: KeyboardLayout = defaultKeyboardLayoutObject;

export const localeMapping = new Map<string, string>([
  ['us', '00000409'], // US keyboard
  ['en_us', '00000409'], // US keyboard
  ['es', '0000040A'], // Spanish keyboard
  ['es_es', '0000040A'], // Spanish keyboard
  ['br', '00000416'], // Portuguese (Brazil ABNT) keyboard
  ['pt_br', '00000416'], // Portuguese (Brazil ABNT) keyboard
  ['latam', '0000080A'], // Latin American keyboard
  ['es_mx', '0000080A'], // Latin American keyboard
  ['pt', '00000816'], // Portuguese keyboard
  ['pt_pt', '00000816'], // Portuguese keyboard
  ['el', '00000408'], // Greek keyboard
  ['el_gr', '00000408'], // Greek keyboard
]);

export const keypadLocation = 3;
