/**
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by generate_keyboard_layouts.js, do not edit manually.

import defaultKeyboardLayoutObject from './layouts/00000409';
import type { KeyboardLayout } from './types';

export type * from './types';
export const defaultKlid = '00000409';
export const defaultKeyboardLayout: KeyboardLayout = defaultKeyboardLayoutObject;

export const localeMapping = new Map<string, string>([
  ['us', '00000409'], // US English
  ['en_us', '00000409'], // US English
  ['gb', '00000809'], // British
  ['en_gb', '00000809'], // British
  ['dk', '00000406'], // Danish
  ['da_dk', '00000406'], // Danish
  ['fr', '0000040C'], // French
  ['fr_fr', '0000040C'], // French
  ['de', '00000407'], // German
  ['de_de', '00000407'], // German
  ['it', '00000410'], // Italian
  ['it_it', '00000410'], // Italian
  ['pt', '00000816'], // Portuguese (Portugal)
  ['pt_pt', '00000816'], // Portuguese (Portugal)
  ['br', '00000416'], // Portuguese (Brazil)
  ['pt_br', '00000416'], // Portuguese (Brazil)
  ['ru', '00000419'], // Russian
  ['ru_ru', '00000419'], // Russian
  ['ua', '00020422'], // Ukrainian
  ['uk_ua', '00020422'], // Ukrainian
  ['es', '0000040A'], // Spanish & Catalan (Spain)
  ['es_es', '0000040A'], // Spanish & Catalan (Spain)
  ['ca_es', '0000040A'], // Spanish & Catalan (Spain)
  ['latam', '0000080A'], // Spanish (Latin America)
  ['ch', '00000807'], // German (Switzerland)
  ['de_ch', '00000807'], // German (Switzerland)
  ['fr_ch', '0000100C'], // French and Italian (Switzerland)
  ['it_ch', '0000100C'], // French and Italian (Switzerland)
]);

export const keypadLocation = 3;
