/**
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by generate_keyboard_layouts.js, do not edit manually.

import usKeyboardLayout from './layouts/us';
import type { KeyboardLayout } from './types';

export type * from './types';
export const defaultKeyboardLayoutName = 'us';
export const defaultKeyboardLayout: KeyboardLayout = usKeyboardLayout;

export const keyboardLayoutNamesMapping = new Map<string, string>([
  ['us', 'us'], // US English
  ['en_us', 'us'], // US English
  ['gb', 'gb'], // British
  ['en_gb', 'gb'], // British
  ['dk', 'dk'], // Danish
  ['da_dk', 'dk'], // Danish
  ['fr', 'fr'], // French
  ['fr_fr', 'fr'], // French
  ['de', 'de'], // German
  ['de_de', 'de'], // German
  ['it', 'it'], // Italian
  ['it_it', 'it'], // Italian
  ['pt', 'pt'], // Portuguese (Portugal)
  ['pt_pt', 'pt'], // Portuguese (Portugal)
  ['br', 'br'], // Portuguese (Brazil)
  ['pt_br', 'br'], // Portuguese (Brazil)
  ['ru', 'ru'], // Russian
  ['ru_ru', 'ru'], // Russian
  ['ua', 'ua'], // Ukrainian
  ['uk_ua', 'ua'], // Ukrainian
  ['es', 'es'], // Spanish & Catalan (Spain)
  ['es_es', 'es'], // Spanish & Catalan (Spain)
  ['ca_es', 'es'], // Spanish & Catalan (Spain)
  ['latam', 'latam'], // Spanish (Latin America)
  ['ch', 'ch'], // German (Switzerland)
  ['de_ch', 'ch'], // German (Switzerland)
  ['fr_ch', 'fr_ch'], // French and Italian (Switzerland)
  ['it_ch', 'fr_ch'], // French and Italian (Switzerland)
]);

export const keypadLocation = 3;
