/**
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable @stylistic/indent */

// Commands generated by generate_cli_commands.js

export const helpMessage: Record<string, string> = {};

helpMessage['close'] =
`playwright-cli close 

Close the page
`;

helpMessage['resize'] =
`playwright-cli resize <width> <height>

Resize the browser window

Parameters:
  <width>           Width of the browser window
  <height>          Height of the browser window
`;

helpMessage['console_messages'] =
`playwright-cli console_messages 

Returns all console messages

Options:
  --level           Level of the console messages to return. Each level includes the messages of more severe levels. Defaults to "info".
`;

helpMessage['handle_dialog'] =
`playwright-cli handle_dialog <accept>

Handle a dialog

Parameters:
  <accept>          Whether to accept the dialog.

Options:
  --prompt-text     The text of the prompt in case of a prompt dialog.
`;

helpMessage['evaluate'] =
`playwright-cli evaluate <function>

Evaluate JavaScript expression on page or element

Parameters:
  <function>        () => { /* code */ } or (element) => { /* code */ } when element is provided

Options:
  --element         Human-readable element description used to obtain permission to interact with the element
  --ref             Exact target element reference from the page snapshot
`;

helpMessage['file_upload'] =
`playwright-cli file_upload 

Upload one or multiple files

Options:
  --paths           The absolute paths to the files to upload. Can be single file or multiple files. If omitted, file chooser is cancelled.
`;

helpMessage['fill_form'] =
`playwright-cli fill_form <fields>

Fill multiple form fields

Parameters:
  <fields>          Fields to fill in
`;

helpMessage['install'] =
`playwright-cli install 

Install the browser specified in the config. Call this if you get an error about the browser not being installed.
`;

helpMessage['press_key'] =
`playwright-cli press_key <key>

Press a key on the keyboard

Parameters:
  <key>             Name of the key to press or a character to generate, such as \`ArrowLeft\` or \`a\`
`;

helpMessage['type'] =
`playwright-cli type <ref> <text>

Type text into editable element

Parameters:
  <ref>             Exact target element reference from the page snapshot
  <text>            Text to type into the element

Options:
  --element         Human-readable element description used to obtain permission to interact with the element
  --submit          Whether to submit entered text (press Enter after)
  --slowly          Whether to type one character at a time. Useful for triggering key handlers in the page. By default entire text is filled in at once.
`;

helpMessage['navigate'] =
`playwright-cli navigate <url>

Navigate to a URL

Aliases: goto, open

Parameters:
  <url>             The URL to navigate to

Options:
  --headed                    run browser in headed mode
`;

helpMessage['navigate_back'] =
`playwright-cli navigate_back 

Go back to the previous page
`;

helpMessage['network_requests'] =
`playwright-cli network_requests 

Returns all network requests since loading the page

Options:
  --include-static  Whether to include successful static resources like images, fonts, scripts, etc. Defaults to false.
`;

helpMessage['mouse_move_xy'] =
`playwright-cli mouse_move_xy <element> <x> <y>

Move mouse to a given position

Parameters:
  <element>         Human-readable element description used to obtain permission to interact with the element
  <x>               X coordinate
  <y>               Y coordinate
`;

helpMessage['mouse_click_xy'] =
`playwright-cli mouse_click_xy <element> <x> <y>

Click left mouse button at a given position

Parameters:
  <element>         Human-readable element description used to obtain permission to interact with the element
  <x>               X coordinate
  <y>               Y coordinate
`;

helpMessage['mouse_drag_xy'] =
`playwright-cli mouse_drag_xy <element> <startX> <startY> <endX> <endY>

Drag left mouse button to a given position

Parameters:
  <element>         Human-readable element description used to obtain permission to interact with the element
  <startX>          Start X coordinate
  <startY>          Start Y coordinate
  <endX>            End X coordinate
  <endY>            End Y coordinate
`;

helpMessage['pdf_save'] =
`playwright-cli pdf_save 

Save page as PDF

Options:
  --filename        File name to save the pdf to. Defaults to \`page-{timestamp}.pdf\` if not specified. Prefer relative file names to stay within the output directory.
`;

helpMessage['run_code'] =
`playwright-cli run_code <code>

Run Playwright code snippet

Parameters:
  <code>            A JavaScript function containing Playwright code to execute. It will be invoked with a single argument, page, which you can use for any page interaction. For example: \`async (page) => { await page.getByRole('button', { name: 'Submit' }).click(); return await page.title(); }\`
`;

helpMessage['take_screenshot'] =
`playwright-cli take_screenshot 

Take a screenshot of the current page. You can't perform actions based on the screenshot, use browser_snapshot for actions.

Aliases: screenshot

Options:
  --type            Image format for the screenshot. Default is png.
  --filename        File name to save the screenshot to. Defaults to \`page-{timestamp}.{png|jpeg}\` if not specified. Prefer relative file names to stay within the output directory.
  --element         Human-readable element description used to obtain permission to screenshot the element. If not provided, the screenshot will be taken of viewport. If element is provided, ref must be provided too.
  --ref             Exact target element reference from the page snapshot. If not provided, the screenshot will be taken of viewport. If ref is provided, element must be provided too.
  --full-page       When true, takes a screenshot of the full scrollable page, instead of the currently visible viewport. Cannot be used with element screenshots.
`;

helpMessage['snapshot'] =
`playwright-cli snapshot 

Capture accessibility snapshot of the current page, this is better than screenshot

Options:
  --filename        Save snapshot to markdown file instead of returning it in the response.
`;

helpMessage['click'] =
`playwright-cli click <ref>

Perform click on a web page

Parameters:
  <ref>             Exact target element reference from the page snapshot

Options:
  --element         Human-readable element description used to obtain permission to interact with the element
  --double-click    Whether to perform a double click instead of a single click
  --button          Button to click, defaults to left
  --modifiers       Modifier keys to press
`;

helpMessage['drag'] =
`playwright-cli drag <startElement> <startRef> <endElement> <endRef>

Perform drag and drop between two elements

Parameters:
  <startElement>    Human-readable source element description used to obtain the permission to interact with the element
  <startRef>        Exact source element reference from the page snapshot
  <endElement>      Human-readable target element description used to obtain the permission to interact with the element
  <endRef>          Exact target element reference from the page snapshot
`;

helpMessage['hover'] =
`playwright-cli hover <ref>

Hover over element on page

Parameters:
  <ref>             Exact target element reference from the page snapshot

Options:
  --element         Human-readable element description used to obtain permission to interact with the element
`;

helpMessage['select_option'] =
`playwright-cli select_option <ref> <values>

Select an option in a dropdown

Parameters:
  <ref>             Exact target element reference from the page snapshot
  <values>          Array of values to select in the dropdown. This can be a single value or multiple values.

Options:
  --element         Human-readable element description used to obtain permission to interact with the element
`;

helpMessage['generate_locator'] =
`playwright-cli generate_locator <ref>

Generate locator for the given element to use in tests

Parameters:
  <ref>             Exact target element reference from the page snapshot

Options:
  --element         Human-readable element description used to obtain permission to interact with the element
`;

helpMessage['tabs'] =
`playwright-cli tabs <action>

List, create, close, or select a browser tab.

Parameters:
  <action>          Operation to perform

Options:
  --index           Tab index, used for close/select. If omitted for close, current tab is closed.
`;

helpMessage['start_tracing'] =
`playwright-cli start_tracing 

Start trace recording
`;

helpMessage['stop_tracing'] =
`playwright-cli stop_tracing 

Stop trace recording
`;

helpMessage['wait_for'] =
`playwright-cli wait_for 

Wait for text to appear or disappear or a specified time to pass

Options:
  --time            The time to wait in seconds
  --text            The text to wait for
  --text-gone       The text to wait for to disappear
`;

helpMessage['verify_element_visible'] =
`playwright-cli verify_element_visible <role> <accessibleName>

Verify element is visible on the page

Parameters:
  <role>            ROLE of the element. Can be found in the snapshot like this: \`- {ROLE} "Accessible Name":\`
  <accessibleName>  ACCESSIBLE_NAME of the element. Can be found in the snapshot like this: \`- role "{ACCESSIBLE_NAME}"\`
`;

helpMessage['verify_text_visible'] =
`playwright-cli verify_text_visible <text>

Verify text is visible on the page. Prefer browser_verify_element_visible if possible.

Parameters:
  <text>            TEXT to verify. Can be found in the snapshot like this: \`- role "Accessible Name": {TEXT}\` or like this: \`- text: {TEXT}\`
`;

helpMessage['verify_list_visible'] =
`playwright-cli verify_list_visible <element> <ref> <items>

Verify list is visible on the page

Parameters:
  <element>         Human-readable list description
  <ref>             Exact target element reference that points to the list
  <items>           Items to verify
`;

helpMessage['verify_value'] =
`playwright-cli verify_value <type> <element> <ref> <value>

Verify element value

Parameters:
  <type>            Type of the element
  <element>         Human-readable element description
  <ref>             Exact target element reference that points to the element
  <value>           Value to verify. For checkbox, use "true" or "false".
`;

export const globalHelp: string =
`playwright-cli - run playwright mcp commands from terminal

Usage: playwright-cli <command> [options]

Core:
  close                       close browser
  resize <width> <height>     resize browser window
  console_messages            get console messages
  handle_dialog <accept>      handle a dialog
  evaluate <function>         evaluate JavaScript
  file_upload                 upload files
  fill_form <fields>          fill form
  press_key <key>             press a key
  type <ref> <text>           type text
  navigate <url>              navigate to a URL
  navigate_back               go back
  network_requests            list network requests
  run_code <code>             run Playwright code
  take_screenshot             take a screenshot
  snapshot                    page snapshot
  click <ref>                 click
  drag <startElement> <startRef> <endElement> <endRef>
                              drag mouse
  hover <ref>                 hover mouse
  select_option <ref> <values>select option
  wait_for                    wait for

Tab management:
  tabs <action>               manage tabs

Browser installation:
  install                     install the browser specified in the config

Coordinate-based:
  mouse_move_xy <element> <x> <y>
                              move mouse
  mouse_click_xy <element> <x> <y>
                              click
  mouse_drag_xy <element> <startX> <startY> <endX> <endY>
                              drag mouse

PDF generation:
  pdf_save                    save as PDF

Tracing:
  start_tracing               start tracing
  stop_tracing                stop tracing

Testing:
  generate_locator <ref>      create locator for element
  verify_element_visible <role> <accessibleName>
                              verify element visible
  verify_text_visible <text>  verify text visible
  verify_list_visible <element> <ref> <items>
                              verify list visible
  verify_value <type> <element> <ref> <value>
                              verify value

Options:
  --help                      show help for a specific command
  --version                   show version information

Examples:
  playwright-cli navigate https://playwright.dev
  playwright-cli snapshot
  playwright-cli click e67
`;

export const aliases: Record<string, string[]> = {
  'navigate': ['goto', 'open'],
  'take_screenshot': ['screenshot'],
};

// End of commands generated section
