name: Deploy trace viewer to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [labeled]
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy-trace-viewer') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Build trace viewer for GitHub Pages
        run: node utils/build/build.js trace-viewer
        env:
          GITHUB_PAGES_BASE: /${{ github.event.repository.name }}/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/playwright-core/lib/vite/traceViewer

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
