# npm publishing (@next, @beta and @latest) is done by the ESRP pipeline,
# see .azure-pipelines/publish.yml
name: "publish release - trace viewer"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 5 * * *"
  push:
    branches:
      - release-*
  release:
    types: [published]

jobs:
  publish-trace-viewer:
    name: "publish Trace Viewer to trace.playwright.dev"
    runs-on: ubuntu-24.04
    if: github.repository == 'microsoft/playwright'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: lts/*
    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: app-token
      with:
        client-id: ${{ vars.PLAYWRIGHT_APP_CLIENT_ID }}
        private-key: ${{ secrets.PLAYWRIGHT_PRIVATE_KEY }}
        repositories: trace.playwright.dev
    - name: Deploy Canary
      if: contains(github.ref, 'main') && github.event.schedule
      run: bash utils/build/deploy-trace-viewer.sh --canary
      env:
        GH_SERVICE_ACCOUNT_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: Deploy Beta
      if: contains(github.ref, 'release') && github.event_name == 'push'
      run: bash utils/build/deploy-trace-viewer.sh --beta
      env:
        GH_SERVICE_ACCOUNT_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: Deploy Stable
      if: github.event_name == 'release' && github.event.action == 'published'
      run: bash utils/build/deploy-trace-viewer.sh --stable
      env:
        GH_SERVICE_ACCOUNT_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: Deploy Stable (manually)
      if: contains(github.ref, 'release') && github.event_name == 'workflow_dispatch'
      run: bash utils/build/deploy-trace-viewer.sh --stable
      env:
        GH_SERVICE_ACCOUNT_TOKEN: ${{ steps.app-token.outputs.token }}
