name: tests docker (release)

on:
  push:
    branches:
      - release-*

jobs:
  test_linux_docker:
    uses: ./.github/workflows/tests_docker.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
