name: "components"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths:
      - 'packages/playwright/**'
      - 'packages/playwright-client/**'
      - 'packages/playwright-core/**'
      - '!packages/playwright-core/src/server/bidi/**'
      - '!packages/playwright-core/src/tools/**'
      - 'packages/playwright-test/**'
      - 'packages/playwright-ct-core/**'
      - 'packages/playwright-ct-react/**'
      - 'packages/playwright-ct-react17/**'
      - 'packages/playwright-ct-solid/**'
      - 'packages/playwright-ct-vue/**'
      - 'packages/html-reporter/**'
      - 'packages/injected/**'
      - 'packages/isomorphic/**'
      - 'packages/protocol/**'
      - 'packages/recorder/**'
      - 'packages/trace/**'
      - 'packages/trace-viewer/**'
      - 'packages/utils/**'
      - 'packages/web/**'
      - 'tests/components/**'
      - 'utils/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/tests_components.yml'
    branches:
      - main
      - release-*

env:
  FORCE_COLOR: 1
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  test_components:
    name: ${{ matrix.os }} - Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20]
        include:
          - os: ubuntu-latest
            node-version: 22
          - os: ubuntu-latest
            node-version: 24
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npx playwright install --with-deps
    - run: npm run ct
