name: Extension

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'packages/playwright-core/src/tools/**'
      - '!packages/playwright-core/src/tools/dashboard/**'
      - '!packages/playwright-core/src/tools/trace/**'
      - 'packages/extension/**'
      - 'tests/extension/**'
      - '.github/workflows/tests_extension.yml'
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'packages/playwright-core/src/tools/**'
      - '!packages/playwright-core/src/tools/dashboard/**'
      - '!packages/playwright-core/src/tools/trace/**'
      - 'packages/extension/**'
      - 'tests/extension/**'
      - '.github/workflows/tests_extension.yml'

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1
  DEBUG: pw:mcp:error

jobs:
  test_extension:
    name: ${{ matrix.os }}
    # The Chrome extension tests require --load-extension, which only works with
    # the chromium channel on macOS.
    environment: ${{ github.event_name == 'push' && 'allow-uploading-flakiness-results' || null }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write   # This is required for OIDC login (azure/login) to succeed
      contents: read    # This is required for actions/checkout to succeed
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/run-test
      with:
        node-version: "22"
        command: npm run build-extension && npm run test-extension
        bot-name: "extension-${{ matrix.os }}"
        flakiness-client-id: ${{ secrets.AZURE_FLAKINESS_DASHBOARD_CLIENT_ID }}
        flakiness-tenant-id: ${{ secrets.AZURE_FLAKINESS_DASHBOARD_TENANT_ID }}
        flakiness-subscription-id: ${{ secrets.AZURE_FLAKINESS_DASHBOARD_SUBSCRIPTION_ID }}
