name: extension

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'packages/playwright-core/src/tools/**'
      - '!packages/playwright-core/src/tools/dashboard/**'
      - '!packages/playwright-core/src/tools/trace/**'
      - 'packages/extension/**'
      - 'tests/extension/**'
      - '.github/workflows/tests_extension.yml'
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'packages/playwright-core/src/tools/**'
      - '!packages/playwright-core/src/tools/dashboard/**'
      - '!packages/playwright-core/src/tools/trace/**'
      - 'packages/extension/**'
      - 'tests/extension/**'
      - '.github/workflows/tests_extension.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  DEBUG: pw:mcp:error

jobs:
  test_extension:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: 22
    - run: npm ci
    - run: npm run build
    - run: npx playwright install --with-deps chromium
    - run: npm run test-extension
    - name: Upload parquet report
      if: ${{ !cancelled() }}
      uses: ./.github/actions/upload-parquet-report
      with:
        job_name: extension-${{ matrix.os }}
